server:
  port: 1002
spring:
  application:
    name: author-backup
  boot:
    admin:
      client:
        url: "http://localhost:1000"
management:
  endpoints:
    web:
      exposure:
        include: "*"
author:
  backup:
    datasource:
      host: localhost
      userName: root
      password: 123456
      database: authorizationmgr